var  categories = [

	{name:"bread", count:0,}
	{name:"rice", count:0,}
	{name:"pasta", count:0,}
	{name:"eggs", count:0,}
	{name:"milk", count:0,}
	{name:"butter", count:0,}
	{name:"flour", count:0,}
	{name:"oil", count:0,}
	{name:"chicken", count:0,}
	{name:"beef", count:0,}
	{name:"pork", count:0,}
	{name:"lamb", count:0,}
	{name:"cod", count:0,}
	{name:"salmon", count:0,}
	{name:"bacon", count:0,}
	{name:"cream", count:0,}
	{name:"peas", count:0,}
	{name:"beans", count:0,}
	{name:"tomato", count:0,}
	{name:"onion", count:0,}
	{name:"garlic", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}	
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}
	{name:"", count:0,}

]